# Generated by Django 3.2.7 on 2021-11-29 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_stop_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='arrive',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='depart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='food',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lodging',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='todos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
    ]
