# Generated by Django 3.2.7 on 2021-11-29 21:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211129_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='food',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None),
        ),
    ]
