# Generated by Django 3.2.7 on 2021-11-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20211129_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['-depart']},
        ),
    ]
